config/routes.rb
Rails.application.routes.draw do
  resources :domains
  resources :people
  get 'batch_revocation/index'
  get 'batch_revocation/destroy'
  resources :certificates
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'certificates/revoke/:id', to: 'certificates#revoke'
  resource :batch_processes
  
  root to: "certificates#index"  
end

app/controllers/batch_revocation_controller.rb
class BatchRevocationController < ApplicationController
  def index
    session[:certificate_ids] = batch_revocation_params[:ids]
    @certificates = Certificate.where id: session[:certificate_ids]
  end

  def destroy   
    certificates = Certificate.where id: session[:certificate_ids]
    file_folder = File.join(Rails.root,'tmp')
    file_name_body = "batch_revocation"
    tsv_file = (File.join(file_folder, "#{file_name_body}.tsv"))
    tsv = ''
    certificates.each do |certificate|
      certificate.assign_attributes(operator_name: form_params[:operator_name], operator_email: form_params[:operator_email], revocation_reason_code: form_params[:revocation_reason_code], revocation_reason: form_params[:revocation_reason])
      tsv << certificate.revoke_tsv
    end
    File.write(tsv_file, tsv, encoding: Encoding::SJIS)
    send_data(File.read(tsv_file), filename: "#{file_name_body}.tsv")
    File.unlink(tsv_file)
    reset_session
  end

  private
  def batch_revocation_params
    params.permit(ids: [])
  end

  def form_params
    params.permit(:operator_name, :operator_email, :revocation_reason_code, :revocation_reason)
  end
end

app/helpers/batch_revocation_helper.rb
module BatchRevocationHelper
end

app/views/batch_revocation/destroy.html.erb
<h1>BatchRevocation#destroy</h1>
<p>Find me in app/views/batch_revocation/destroy.html.erb</p>

app/views/batch_revocation/index.html.erb
<h1>一括失効</h1>
<p id="notice"><%= notice %></p>


<%= link_to '一覧に戻る', certificates_path, class: "btn btn-primary" %>
<%= link_to 'UPKIへ', 'https://scia.secomtrust.net/upki-odcert/lra/SSLLogin.do', class: "btn btn-success" %>
　  <div class="container">
<%= form_with url: batch_revocation_destroy_path, method: :get do |f| %>
<%= f.submit '一括更新用TSVダウンロード', class: "btn btn-danger"  %>
  <div class="field form-group">
    <%= f.label :operator_name, '管理者氏名', class: 'form-label' %>
    <%= f.text_field :operator_name, class: 'form-control' %>
  </div>
  
  <div class="field form-group">
    <%= f.label :operator_email, '管理者mail（必須）', class: 'form-label' %>
    <%= f.text_field :operator_email, class: 'form-control', required: true %>
  </div>
  <div class="field form-group">
    <%= f.label :revocation_reason_code, '失効理由', class: 'form-label'  %>
    <%= f.select :revocation_reason_code, {'未定義': 0, '鍵の危殆化': 1, '主体DNの変更': 2, '証明書の更新または証明書記載内容の変更': 3, '証明書の利用終了': 4}, class: 'form-control', required: true %>
  </div>
  <div class="field form-group">
    <%= f.label :revocation_reason_code, '失効理由コメント', class: 'form-label'  %>
    <%= f.text_field :revocation_reason, class: 'form-control' %>
  </div>
<% end %>
</div>
<table>
  <table class="table table-responsible">
  <thead>
    <tr>
      <th>サーバFQDN</th>
      <th>発行・更新申請日</th>
      <th>氏名</th>
      <th>e-mail</th>
      <th>Software</th>
      <th>有効開始</th>
      <th>有効期限</th>
      <!-- <th>URL期限</th> -->
      <!-- <th>失効処理完了日時</th> -->
      <!-- <th>最終更新日</th> -->
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @certificates.each do |certificate| %>
       <tr class=<%= certificate_color(certificate) %> >
         <td><%= certificate.operator_fqdn %></td>
        <td><%= certificate.submitted.to_s(:jp_order) %></td>
        <td><%= certificate.operator_name %></td>
        <td><%= certificate.operator_email %></td>
        <td><%= certificate.operator_software %></td>
	<% if certificate.cert_start %>
          <td><%= l certificate.cert_start %></td>
	<% else %>
          <td><%= certificate.cert_start %></td>
	<% end %>
	<% if certificate.cert_exp %>
          <td><%= l certificate.cert_exp %></td>
	<% else %>
          <td><%= certificate.cert_exp %></td>
	<% end %>
	<!-- <% if certificate.url_exp %> -->
        <!--   <td><%= l certificate.url_exp %></td> -->
	<!-- <% else %> -->
        <!--   <td><%= certificate.url_exp %></td> -->
	<!-- <% end %> -->
	<% if certificate.revocation_completed %>
         <td><%= l certificate.revocation_completed %></td>
	<% else %>
         <td><%= certificate.revocation_completed %></td>
	<% end %>
        <!-- <td><%= l certificate.last_updated %></td> -->
        <!-- <td><%= link_to '詳細', certificate, class: "btn btn-info"  %></td> -->
        <!-- <td><%= link_to '更新', edit_certificate_path(certificate), class: update_button_class(certificate) %></td> -->
        <!-- <td><%= link_to '失効', certificate_path(certificate), method: :delete, class: delete_button_class(certificate) %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>