config/routes.rb
Rails.application.routes.draw do
  resources :domains
  resources :people
  get 'batch_revocation/index'
  get 'batch_revocation/destroy'
  resources :certificates
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'certificates/revoke/:id', to: 'certificates#revoke'
  resource :batch_processes
  
  root to: "certificates#index"  
end

app/models/domain.rb
class Domain < ApplicationRecord
  has_many :certificates
  belongs_to :person
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: %i[ show edit update destroy ]

  # GET /domains or /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1 or /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains or /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: "Domain was successfully created." }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1 or /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: "Domain was successfully updated." }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1 or /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: "Domain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def domain_params
      params.require(:domain).permit(:full_name, :person_id)
    end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_with(model: domain) do |form| %>
  <% if domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
        <% domain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='container'>
    <form class='form-horizontal'>
      <div class="field form-group">
	<%= form.label :full_name, 'FQDN', class: 'form-label' %>
	<%= form.text_field :full_name, class: 'form-control' %>
      </div>
      
      <div class="field form-group">
	<%= form.label :person_id, '担当者', class: 'form-lable' %>
	<%= form.text_field :person_id, class: 'form-control' %>
      </div>
      
      <div class="actions">
	<%= form.submit '新規ドメイン作成', class: 'btn btn-primary' %>
      </div>
    </form>
  </div>
<% end %>
  

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ドメイン一覧</h1>

<table class="table table-responsible">
  <thead>
    <tr>
      <th>FQDN</th>
      <th>証明書期限</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.full_name %></td>
        <td><%= '2022-03-07' %></td>
        <td><%= link_to '詳細', domain %></td>
        <!-- <td><%= link_to '更新', edit_domain_path(domain) %></td> -->
        <!-- <td><%= link_to '', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規サーバ登録申請', new_domain_path, class: "btn btn-primary" %>

app/views/domains/new.html.erb
<h1>新規ドメイン申請</h1>

<%= render 'form', domain: @domain %>

<%= link_to '一覧に戻る', domains_path, class: 'btn btn-primary' %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @domain.full_name %>
</p>

<p>
  <strong>Person:</strong>
  <%= @domain.person_id %>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>