config/routes.rb
Rails.application.routes.draw do
  resources :domains
  resources :people
  get 'batch_revocation/index'
  get 'batch_revocation/destroy'
  resources :certificates
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'certificates/revoke/:id', to: 'certificates#revoke'
  resource :batch_processes
  
  root to: "certificates#index"  
end

app/models/certificate.rb
require 'openssl'
require 'csv'
require 'date'

class Certificate < ApplicationRecord
#  attr_accessor :software

  validates :operator_fqdn, presence: true
  validates :operator_email, presence: true
  validates :operator_software, presence: true

  def cipher_key
    @cipher_key ||= OpenSSL::PKey::RSA.generate(2048)
  end

  def cipher_key_pem(passphrase = nil)
    if passphrase.present?
      cipher_key.to_pem(OpenSSL::Cipher.new('AES-256-CBC'), passphrase)
    else
      cipher_key.to_pem
    end
  end

  def dn
    if subject_dn
      subject_dn
    else
      @dn = "CN=#{operator_fqdn},"
      @dn += "OU=#{Profile.ou}," if Profile.ou
      @dn += "O=#{Profile.o},"
      @dn += "L=#{Profile.l},"
      @dn += "ST=#{Profile.st},"
      @dn += "C=#{Profile.c}"
    end
  end

  def dn2entries
    dn.delete("\n").split(',').map do |item|
      item.split('=')
    end
  end

  def csr_main
    csr = OpenSSL::X509::Request.new
    name = OpenSSL::X509::Name.new(dn2entries)
    csr.subject = name
    csr.public_key =cipher_key.public_key
#    factory = OpenSSL::X509::ExtensionFactory.new
    csr.sign(cipher_key, 'sha256').to_pem.lines[1..-2].join.delete("\n")
  end

  def new_tsv
    "#{dn}\t3\t\t\t\t\t#{csr_main}\t#{operator_name}\t#{operator_affiliation}\t#{operator_email}\t#{operator_fqdn}\t#{operator_software}\t\n"
  end

  def update_tsv
    "#{dn}\t3\t\t#{serial_no}\t\t\t#{csr_main}\t#{operator_name}\t#{operator_affiliation}\t#{operator_email}\t#{operator_fqdn}\t#{operator_software}\t\n"
  end

  def revoke_tsv
    "#{dn}\t\t\t#{serial_no}\t#{revocation_reason_code}\t#{revocation_reason}\t\t\t\t#{operator_email}\t\t\t\n"
  end

  def self.read_tsv(tsv_file)
    CSV.open(tsv_file, 'r', headers: :first_row, col_sep: "\t", encoding: Encoding::SHIFT_JIS).each do |certificate|
      Certificate.create(
        apply_id: certificate[0],
        operation_id: certificate[1],
        ignore_flag: certificate[2],
        subject_dn: certificate[3],
        domain_id: certificate[4],
        submitted: certificate[5], #.sub("\s", 'T')+"+09:00",
        completed: certificate[6],
        operator_id: certificate[7],
        category: certificate[8],
        task_model: certificate[9],
        profile_id: certificate[10],
        status: certificate[11],
        operator_name: certificate[12],
        operator_affiliation: certificate[13],
        operator_email: certificate[14],
        operator_fqdn: certificate[15],
        operator_software: certificate[16],
        csr: certificate[17],
        dnsname: certificate[18],
        comfirmed_items_flag: certificate[19],
        transaction_id: certificate[20],
        api_erro_code: certificate[21],
        cetification: certificate[22],
        serial_no: certificate[23],
        finger_print: certificate[24],
        cert_start: certificate[25],
        cert_exp: certificate[26],
        url_exp: certificate[27],
        access_pin: certificate[28],
        other_subject_address1: certificate[29],
        other_subject_address2: certificate[30],
        revocation_id: certificate[31],
        revocation_operation_id: certificate[32],
        revocation_submitted: certificate[33],
        revocation_completed: certificate[34],
        revocation_operator_id: certificate[35],
        revocation_reason_code: certificate[36],
        revocation_reason: certificate[37],
        revocation_confirm_code: certificate[38],
        revocation_transaction_id: certificate[39],
        revocation_authority_error_code: certificate[40],
        revocation_operator_email: certificate[41],
        old_certificate_serial_no: certificate[42],
        certificate_replace_mail_flag: certificate[43],
        download_method: certificate[44],
        last_updated: certificate[45]
      )
    end
  end
end

app/controllers/certificates_controller.rb
require 'zip'

class CertificatesController < ApplicationController
  before_action :set_certificate, only: %i[ show edit update destroy ]

  # GET /certificates or /certificates.json
  def index
    @certificates = Certificate.all
  end

  # GET /certificates/1 or /certificates/1.json
  def show
  end

  # GET /certificates/new
  def new
    @certificate = Certificate.new(operator_email: Profile.email, operator_name: Profile.name, operator_affiliation: Profile.o)
  end

  # GET /certificates/1/edit
  def edit
  end


  # POST /certificates or /certificates.json
  def create
    @certificate = Certificate.new(certificate_params.except(:passphrase))
    
    if @certificate.valid?
      generate_and_download_certificate_zip(@certificate, passphrase_param)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /certificates/1 or /certificates/1.json
  def update
    if @certificate.update(certificate_params.except(:passphrase))
      generate_and_download_certificate_zip(@certificate, passphrase_param, :update)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /certificates/1 or /certificates/1.json
  def destroy
  end

  def revoke
    certificate = Certificate.find(params[:id])
    certificate.assign_attributes(certificate_params)
    file_folder = File.join(Rails.root,'tmp')
    file_name_body = "#{certificate.operator_fqdn}"
    tsv = File.join(file_folder, "#{file_name_body}.tsv")
    File.write(tsv, certificate.revoke_tsv)
    send_data(File.read(tsv), filename: "#{file_name_body}.tsv")
    File.unlink(tsv)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    # パスフレーズは一時的にメモリ内でのみ使用し、データベースには保存しない
    def passphrase_param
      params.dig(:certificate, :passphrase)
    end

    # 証明書ファイル生成とダウンロード処理の共通メソッド
    # セキュリティ: 秘密鍵は一時ファイルとして生成され、処理後すぐに削除される
    def generate_and_download_certificate_zip(certificate, passphrase, action_type = :create)
      file_folder = File.join(Rails.root, 'tmp')
      file_name_body = certificate.operator_fqdn
      
      private_key = File.join(file_folder, "#{file_name_body}.key")
      zip = File.join(file_folder, "#{file_name_body}.zip")
      tsv = File.join(file_folder, "#{file_name_body}.tsv")

      begin
        # 秘密鍵とTSVファイルを一時的に生成
        File.write(private_key, certificate.cipher_key_pem(passphrase))
        tsv_content = action_type == :update ? certificate.update_tsv : certificate.new_tsv
        File.write(tsv, tsv_content)
        
        target_files = [private_key, tsv]

        # ZIPファイル作成
        ::Zip::File.open(zip, Zip::File::CREATE) do |zipfile|
          target_files.each do |file|
            zipfile.add File.basename(file), file
          end
        end

        # ダウンロード送信
        send_data(File.read(zip),
                  filename: "#{file_name_body}.zip",
                  type: 'application/zip',
                  disposition: 'attachment')
      ensure
        # セキュリティ: 一時ファイルを確実に削除
        cleanup_temporary_files([zip, private_key, tsv])
        # パスフレーズ変数をクリア
        passphrase = nil
      end
    end

    # 一時ファイルの安全な削除
    def cleanup_temporary_files(files)
      files.each do |file|
        File.unlink(file) if File.exist?(file)
      end
    end

    # Only allow a list of trusted parameters through.
    # passphraseは許可するが.except(:passphrase)で明示的に除外してデータベースに保存しない
    def certificate_params
      params.require(:certificate).permit(:id, :apply_id, :operation_id, :ignore_flag, :subject_dn, :domain_id, :submitted, :completed, :operator_id, :category, :task_model, :profile_id, :status, :operator_name, :operator_affiliation, :operator_email, :operator_fqdn, :operator_software, :csr, :dnsname, :comfirmed_items_flag, :transaction_id, :api_erro_code, :cetification, :serial_no, :finger_print, :cert_start, :cert_exp, :access_pin, :other_subject_address1, :other_subject_address2, :revocation_id, :revocation_submission, :revocation_completed, :revocation_operator_id, :revocation_reason_code, :revocation_reason, :revocation_confirm_code, :revocation_transaction_id, :revocation_authority_error_code, :revocation_operator_email, :old_certificate_serial_no, :certificate_replace_mail_flag, :download_method, :last_updated, :upload_file, :passphrase)
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
  def certificate_color(certificate)
    if certificate.revocation_completed
      'table-dark'
    elsif certificate.cert_exp
      if certificate.cert_exp < Time.now
        'table-danger'
      elsif certificate.cert_exp < Time.now.next_month
        'table-warning'
      else
        'table-success'
      end
    else
      'table-success'
    end
  end

  def update_button_class(certificate)
    if certificate.revocation_completed
      'btn disabled'
    else
      'btn btn-primary'
    end
  end

  def delete_button_class(certificate)
    if certificate.revocation_completed
      'btn disabled'
    else
      'btn btn-danger'
    end
  end

end

app/views/certificates/_edit_form.html.erb
<%= form_with(model: certificate, local: true, data: { turbo: false }) do |form| %>
  <% if certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
        <% certificate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
　  <div class="container">
    <form class="form-horizontal">
　
  <div class="field form-group">
    <%= form.label :operator_fqdn, '申請するサーバのFQDN（必須）', class: 'form-label' %>
    <%= form.text_field :operator_fqdn, readonly: true, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= form.label :subject_dn, '主体者DN', class: 'form-label' %>
    <%= form.text_field :subject_dn, class: 'form-control' %>
  </div>
  
  <div class="field form-group">
    <%= form.label :serial_no, '発行・更新申請-シリアル番号', class: 'form-label' %>
    <%= form.text_field :serial_no, readonly: true, class: 'form-control' %>
  </div>
  
  <div class="field form-group">
    <%= form.label :operator_name, '管理者氏名', class: 'form-label' %>
    <%= form.text_field :operator_name, class: 'form-control' %>
  </div>
  
  <div class="field form-group">
    <%= form.label :operator_affiliation, '管理者所属', class: 'form-label' %>
    <%= form.text_field :operator_affiliation, readonly: true, class: 'form-control' %>
  </div>
  
  <div class="field form-group">
    <%= form.label :operator_email, '管理者mail（必須）', class: 'form-label' %>
    <%= form.text_field :operator_email, class: 'form-control', required: true %>
  </div>
  
  
  <div class="field form-group">
    <%= form.label :operator_software, '利用管理者ソフトウェア名・バージョン（必須）', class: 'form-label'  %>
    <%= form.text_field :operator_software, class: 'form-control', required: true %>
  </div>
  
  <div class="field form-group">
    <%= form.label :passphrase, 'パスフレーズ', class: 'form-label'  %>
    <%= form.password_field :passphrase, class: 'form-control' %>
  </div>
  
  <!-- <div class="field form-group"> -->
    <!--   <%= form.label :dnsname, 'dNSName', class: 'form-label' %> -->
    <!--   <%= form.text_field :dnsname, class: 'form-control' %> -->
    <!-- </div> -->
  
  
  <div class="actions">
    <%= form.submit '証明書更新申請様式ダウンロード', class: 'btn btn-primary' %>
  </div>
    </form>
    </div>
<% end %>
      

app/views/certificates/_new_form.html.erb
<%= form_with(model: certificate, local: true, data: { turbo: false }) do |form| %>
  <% if certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
        <% certificate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <form class="form-horizontal">
      <div class="field form-group">
	<%= form.label :operator_fqdn, '申請するサーバのFQDN（必須）', class: 'form-label' %>
	<%= form.text_field :operator_fqdn, class: 'form-control', required: true %>
      </div>
      
      
      <div class="field form-group">
	<%= form.label :operator_name, '管理者氏名', class: 'form-label' %>
	<%= form.text_field :operator_name, class: 'form-control' %>
      </div>
      
      <div class="field form-group">
	<%= form.label :operator_affiliation, '管理者所属', class: 'form-label' %>
	<%= form.text_field :operator_affiliation, class: 'form-control' %>
      </div>
      
      <div class="field form-group">
	<%= form.label :operator_email, '管理者mail（必須）', class: 'form-label' %>
	<%= form.text_field :operator_email, class: 'form-control', required: true %>
      </div>
      
      
      <div class="field form-group">
	<%= form.label :operator_software, '利用管理者ソフトウェア名・バージョン（必須）', class: 'form-label'  %>
	<%= form.text_field :operator_software, class: 'form-control', required: true %>
      </div>
      
      <div class="field form-group">
	<%= form.label :passphrase, 'パスフレーズ', class: 'form-label'  %>
	<%= form.password_field :passphrase, class: 'form-control' %>
      </div>
      
      <!-- <div class="field form-group"> -->
	<!--   <%= form.label :dnsname, 'dNSName', class: 'form-label' %> -->
	<!--   <%= form.text_field :dnsname, class: 'form-control' %> -->
	<!-- </div> -->
      
      
      <div class="actions">
	<%= form.submit '新規証明書申請様式ダウンロード', class: 'btn btn-primary' %>
      </div>
    </form>
  </div>
  <% end %>
  

app/views/certificates/delete.html.erb
test

app/views/certificates/destroy.html.erb
<h1>サーバ証明書失効</h1>

<%= form_with(model: @certificate, method: :post, url: {action: 'revoke'}) do |form| %>
  <% if @certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
        <% certificate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <form class="form-horizontal">
      <div class="field form-group">
    <%= form.label :operator_fqdn, '申請するサーバのFQDN（必須）', class: 'form-label' %>
    <%= form.text_field :operator_fqdn, readonly: true, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= form.label :subject_dn, '主体者DN', class: 'form-label' %>
    <%= form.text_field :subject_dn, readonly: true, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :serial_no, '発行・更新申請-シリアル番号', class: 'form-label' %>
    <%= form.text_field :serial_no, readonly: true, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :operator_email, '管理者mail', class: 'form-label' %>
    <%= form.text_field :operator_email, class: 'form-control' %>
  </div>


  <div class="field form-group">
    <%= form.label :revocation_reason_code, '失効理由', class: 'form-label'  %>
    <%= form.select :revocation_reason_code, {'未定義': 0, '鍵の危殆化': 1, '主体DNの変更': 2, '証明書の更新または証明書記載内容の変更': 3, '証明書の利用終了': 4}, class: 'form-control', required: true %>
  </div>
  <div class="field form-group">
    <%= form.label :revocation_reason_code, '失効理由コメント', class: 'form-label'  %>
    <%= form.text_field  :revocation_reason, class: 'form-control' %>
  </div>
  <!-- <strong>失効理由コメント:</strong> -->
  <!-- <%= @certificate.revocation_reason %> -->



  <!-- <div class="field form-group"> -->
  <!--   <%= form.label :dnsname, 'dNSName', class: 'form-label' %> -->
  <!--   <%= form.text_field :dnsname, class: 'form-control' %> -->
  <!-- </div> -->


  <div class="actions">
    <%= form.submit '失効申請様式ダウンロード', class: 'btn btn-primary' %>
  </div>
  </div>
<% end %>
<%= link_to 'サーバ詳細', @certificate, class: "btn btn-primary" %> 
<%= link_to '一覧に戻る', certificates_path, class: "btn btn-primary" %>
<%= link_to 'UPKIへ', 'https://scia.secomtrust.net/upki-odcert/lra/SSLLogin.do', class: "btn btn-success" %>

app/views/certificates/edit.html.erb
<h1>証明書更新</h1>

<%= render 'edit_form', certificate: @certificate %>

<%= link_to 'サーバ詳細', @certificate, class: "btn btn-primary" %> 
<%= link_to '一覧に戻る', certificates_path, class: "btn btn-primary" %>
<%= link_to 'UPKIへ', 'https://scia.secomtrust.net/upki-odcert/lra/SSLLogin.do', class: "btn btn-success" %>

app/views/certificates/index.html.erb
<p id="notice"><%= notice %></p>
<h1>サーバ証明書一覧</h1>

<%= link_to '新規証明書発行', new_certificate_path, class: "btn btn-primary" %>
<%= link_to '一括更新(TSVアップロード)', batch_processes_path, method: :put, class: "btn btn-primary" %>
<%= form_with url: batch_revocation_index_path, method: :get do |form| %>
  <%= form.submit '一括失効処理', class: "btn btn-danger" %>
<table class="table table-responsible">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3">利用管理者</th>
      <th colspan="2">証明書</th>
      <!-- <th></th> -->
      <th></th>
      <!-- <th></th> -->
      <th colspan="3"></th>
    </tr>
    <tr>
      <th>失効対象</th>
      <th>サーバFQDN</th>
      <th>発行・更新申請日</th>
      <th>氏名</th>
      <th>e-mail</th>
      <th>Software</th>
      <th>有効開始</th>
      <th>有効期限</th>
      <!-- <th>URL期限</th> -->
      <th>失効処理完了日時</th>
      <!-- <th>最終更新日</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certificates.each do |certificate| %>
       <tr class=<%= certificate_color(certificate) %> >
	   <% if certificate.revocation_completed %>
             <td class="checkbox hide-when-print disabled"/>
	     <%= check_box_tag "ids[]", false, false, {disabled: true} %>
	   <% else %>
	     <td class="checkbox hide-when-print"/>
	     <%= check_box_tag 'ids[]', certificate.id %>
	   <% end %>
	 </td>
        <td><%= certificate.operator_fqdn %></td>
        <td><%= certificate.submitted&.strftime('%Y/%m/%d %H:%M:%S') %></td>
        <td><%= certificate.operator_name %></td>
        <td><%= certificate.operator_email %></td>
        <td><%= certificate.operator_software %></td>
	<% if certificate.cert_start %>
          <td><%= l certificate.cert_start %></td>
	<% else %>
          <td><%= certificate.cert_start %></td>
	<% end %>
	<% if certificate.cert_exp %>
          <td><%= l certificate.cert_exp %></td>
	<% else %>
          <td><%= certificate.cert_exp %></td>
	<% end %>
	<!-- <% if certificate.url_exp %> -->
        <!--   <td><%= l certificate.url_exp %></td> -->
	<!-- <% else %> -->
        <!--   <td><%= certificate.url_exp %></td> -->
	<!-- <% end %> -->
	<% if certificate.revocation_completed %>
         <td><%= l certificate.revocation_completed %></td>
	<% else %>
         <td><%= certificate.revocation_completed %></td>
	<% end %>
        <!-- <td><%= l certificate.last_updated %></td> -->
        <td><%= link_to '詳細', certificate, class: "btn btn-info"  %></td>
        <td><%= link_to '更新', edit_certificate_path(certificate), class: update_button_class(certificate) %></td>
        <td><%= link_to '失効', certificate_path(certificate), method: :delete, class: delete_button_class(certificate) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

app/views/certificates/new.html.erb
<h1>新規証明書申請</h1>

<%= render 'new_form', certificate: @certificate %>

<%= link_to '一覧に戻る', certificates_path, class: "btn btn-primary" %>
<%= link_to 'UPKIへ', 'https://scia.secomtrust.net/upki-odcert/lra/SSLLogin.do', class: "btn btn-success" %>

app/views/certificates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>発行・更新申請-申請ID:</strong>
  <%= @certificate.apply_id %>
</p>

<p>
  <strong>発行・更新申請-操作ID:</strong>
  <%= @certificate.operation_id %>
</p>

<p>
  <strong>ignoreInvalidRecordフラグ:</strong>
  <%= @certificate.ignore_flag %>
</p>
<p>
  <strong>主体者DN:</strong>
  <%= @certificate.subject_dn %>
</p>

<p>
  <strong>ドメインID:</strong>
  <%= @certificate.domain_id %>
</p>

<p>
  <strong>発行・更新申請-日時:</strong>
  <%= @certificate.submitted %>
</p>

<p>
  <strong>発行・更新申請-処理完了日時:</strong>
  <%= @certificate.completed %>
</p>

<p>
  <strong>発行・更新申請-登録担当者ID:</strong>
  <%= @certificate.operator_id %>
</p>

<p>
  <strong>申請種別:</strong>
  <%= @certificate.category %>
</p>

<p>
  <strong>業務モデル:</strong>
  <%= @certificate.task_model %>
</p>

<p>
  <strong>証明書プロファイルID:</strong>
  <%= @certificate.profile_id %>
</p>

<p>
  <strong>状態:</strong>
  <%= @certificate.status %>
</p>

<p>
  <strong>利用管理者氏名:</strong>
  <%= @certificate.operator_name %>
</p>

<p>
  <strong>利用管理者所属:</strong>
  <%= @certificate.operator_affiliation %>
</p>

<p>
  <strong>利用管理者mail:</strong>
  <%= @certificate.operator_email %>
</p>

<p>
  <strong>利用管理者FQDN:</strong>
  <%= @certificate.operator_fqdn %>
</p>

<p>
  <strong>利用管理者ソフトウェア名・バージョン:</strong>
  <%= @certificate.operator_software %>
</p>

<p>
  <strong>CSR:</strong>
  <%= @certificate.csr %>
</p>

<p>
  <strong>dNSName:</strong>
  <%= @certificate.dnsname %>
</p>

<p>
  <strong>発行・更新申請-確認項目フラグ:</strong>
  <%= @certificate.comfirmed_items_flag %>
</p>

<p>
  <strong>発行・更新申請-トランザクションID:</strong>
  <%= @certificate.transaction_id %>
</p>

<p>
  <strong>発行・更新申請-認証局連携APIエラーコード:</strong>
  <%= @certificate.api_erro_code %>
</p>

<p>
  <strong>発行・更新申請-証明書:</strong>
  <%= @certificate.cetification %>
</p>

<p>
  <strong>発行・更新申請-シリアル番号:</strong>
  <%= @certificate.serial_no %>
</p>

<p>
  <strong>発行・更新申請-FingerPrint:</strong>
  <%= @certificate.finger_print %>
</p>

<p>
  <strong>発行・更新申請-証明書有効開始:</strong>
  <%= @certificate.cert_start %>
</p>

<p>
  <strong>発行・更新申請-証明書有効期限:</strong>
  <%= @certificate.cert_exp %>
</p>

<p>
  <strong>URL期限:</strong>
  <%= @certificate.url_exp %>
</p>

<p>
  <strong>アクセスPIN:</strong>
  <%= @certificate.access_pin %>
</p>

<p>
  <strong>その他送信先アドレス:</strong>
  <%= @certificate.other_subject_address1 %>
</p>

<p>
  <strong>その他送信先アドレス2:</strong>
  <%= @certificate.other_subject_address2 %>
</p>

<p>
  <strong>失効申請-申請ID:</strong>
  <%= @certificate.revocation_id %>
</p>

<p>
  <strong>失効申請-操作ID:</strong>
  <%= @certificate.revocation_operation_id %>
</p>

<p>
  <strong>失効申請-日時:</strong>
  <%= @certificate.revocation_submitted %>
</p>

<p>
  <strong>失効申請-処理完了日時:</strong>
  <%= @certificate.revocation_completed %>
</p>

<p>
  <strong>失効申請-登録担当者ID:</strong>
  <%= @certificate.revocation_operator_id %>
</p>

<p>
  <strong>失効申請-失効理由コード:</strong>
  <%= @certificate.revocation_reason_code %>
</p>

<p>
  <strong>失効申請-失効理由コメント:</strong>
  <%= @certificate.revocation_reason %>
</p>

<p>
  <strong>失効申請-確認項目フラグ:</strong>
  <%= @certificate.revocation_confirm_code %>
</p>

<p>
  <strong>失効申請-トランザクションID:</strong>
  <%= @certificate.revocation_transaction_id %>
</p>

<p>
  <strong>失効申請-認証局連携APIエラーコード:</strong>
  <%= @certificate.revocation_authority_error_code %>
</p>

<p>
  <strong>失効申請-利用管理者mail:</strong>
  <%= @certificate.revocation_operator_email %>
</p>

<p>
  <strong>旧証明書シリアル番号:</strong>
  <%= @certificate.old_certificate_serial_no %>
</p>

<p>
  <strong>証明書リプレース依頼メール送信フラグ:</strong>
  <%= @certificate.certificate_replace_mail_flag %>
</p>

<p>
  <strong>ダウンロード方法:</strong>
  <%= @certificate.download_method %>
</p>

<p>
  <strong>最終更新日:</strong>
  <%= @certificate.last_updated %>
</p>

<%= link_to '更新処理', edit_certificate_path(@certificate), class: update_button_class(@certificate) %>
<%= link_to '失効処理', certificate_path(@certificate), method: :delete, class: delete_button_class(@certificate) %>
<%= link_to '一覧に戻る', certificates_path, class: "btn btn-primary" %>